/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminInviteRouteImport } from './routes/admin/invite'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedTablesIndexRouteImport } from './routes/_authenticated/tables/index'
import { Route as AuthenticatedPagesIndexRouteImport } from './routes/_authenticated/pages/index'
import { Route as AuthenticatedJournalIndexRouteImport } from './routes/_authenticated/journal/index'
import { Route as AuthenticatedTablesTableIdRouteImport } from './routes/_authenticated/tables/$tableId'
import { Route as AuthenticatedPagesPageIdRouteImport } from './routes/_authenticated/pages/$pageId'
import { Route as AuthenticatedJournalLayoutRouteImport } from './routes/_authenticated/journal/_layout'
import { Route as AuthenticatedJournalPageIdRouteImport } from './routes/_authenticated/journal/$pageId'
import { Route as AuthenticatedTablesTableIdSettingsRouteImport } from './routes/_authenticated/tables/$tableId/settings'
import { Route as AuthenticatedTablesTableIdRowsRowIdRouteImport } from './routes/_authenticated/tables/$tableId/rows/$rowId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/admin/invite',
  path: '/admin/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTablesIndexRoute =
  AuthenticatedTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagesIndexRoute = AuthenticatedPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalIndexRoute =
  AuthenticatedJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTablesTableIdRoute =
  AuthenticatedTablesTableIdRouteImport.update({
    id: '/tables/$tableId',
    path: '/tables/$tableId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagesPageIdRoute =
  AuthenticatedPagesPageIdRouteImport.update({
    id: '/pages/$pageId',
    path: '/pages/$pageId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalLayoutRoute =
  AuthenticatedJournalLayoutRouteImport.update({
    id: '/journal/_layout',
    path: '/journal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalPageIdRoute =
  AuthenticatedJournalPageIdRouteImport.update({
    id: '/journal/$pageId',
    path: '/journal/$pageId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTablesTableIdSettingsRoute =
  AuthenticatedTablesTableIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTablesTableIdRoute,
  } as any)
const AuthenticatedTablesTableIdRowsRowIdRoute =
  AuthenticatedTablesTableIdRowsRowIdRouteImport.update({
    id: '/rows/$rowId',
    path: '/rows/$rowId',
    getParentRoute: () => AuthenticatedTablesTableIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/journal/$pageId': typeof AuthenticatedJournalPageIdRoute
  '/journal': typeof AuthenticatedJournalLayoutRoute
  '/pages/$pageId': typeof AuthenticatedPagesPageIdRoute
  '/tables/$tableId': typeof AuthenticatedTablesTableIdRouteWithChildren
  '/journal/': typeof AuthenticatedJournalIndexRoute
  '/pages/': typeof AuthenticatedPagesIndexRoute
  '/tables/': typeof AuthenticatedTablesIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tables/$tableId/settings': typeof AuthenticatedTablesTableIdSettingsRoute
  '/tables/$tableId/rows/$rowId': typeof AuthenticatedTablesTableIdRowsRowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/journal/$pageId': typeof AuthenticatedJournalPageIdRoute
  '/journal': typeof AuthenticatedJournalIndexRoute
  '/pages/$pageId': typeof AuthenticatedPagesPageIdRoute
  '/tables/$tableId': typeof AuthenticatedTablesTableIdRouteWithChildren
  '/pages': typeof AuthenticatedPagesIndexRoute
  '/tables': typeof AuthenticatedTablesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tables/$tableId/settings': typeof AuthenticatedTablesTableIdSettingsRoute
  '/tables/$tableId/rows/$rowId': typeof AuthenticatedTablesTableIdRowsRowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/invite': typeof AdminInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/journal/$pageId': typeof AuthenticatedJournalPageIdRoute
  '/_authenticated/journal/_layout': typeof AuthenticatedJournalLayoutRoute
  '/_authenticated/pages/$pageId': typeof AuthenticatedPagesPageIdRoute
  '/_authenticated/tables/$tableId': typeof AuthenticatedTablesTableIdRouteWithChildren
  '/_authenticated/journal/': typeof AuthenticatedJournalIndexRoute
  '/_authenticated/pages/': typeof AuthenticatedPagesIndexRoute
  '/_authenticated/tables/': typeof AuthenticatedTablesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tables/$tableId/settings': typeof AuthenticatedTablesTableIdSettingsRoute
  '/_authenticated/tables/$tableId/rows/$rowId': typeof AuthenticatedTablesTableIdRowsRowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/calendar'
    | '/dashboard'
    | '/settings'
    | '/admin/invite'
    | '/auth/callback'
    | '/journal/$pageId'
    | '/journal'
    | '/pages/$pageId'
    | '/tables/$tableId'
    | '/journal/'
    | '/pages/'
    | '/tables/'
    | '/tasks/'
    | '/tables/$tableId/settings'
    | '/tables/$tableId/rows/$rowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/calendar'
    | '/dashboard'
    | '/settings'
    | '/admin/invite'
    | '/auth/callback'
    | '/journal/$pageId'
    | '/journal'
    | '/pages/$pageId'
    | '/tables/$tableId'
    | '/pages'
    | '/tables'
    | '/tasks'
    | '/tables/$tableId/settings'
    | '/tables/$tableId/rows/$rowId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/admin/invite'
    | '/auth/callback'
    | '/_authenticated/journal/$pageId'
    | '/_authenticated/journal/_layout'
    | '/_authenticated/pages/$pageId'
    | '/_authenticated/tables/$tableId'
    | '/_authenticated/journal/'
    | '/_authenticated/pages/'
    | '/_authenticated/tables/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tables/$tableId/settings'
    | '/_authenticated/tables/$tableId/rows/$rowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/admin/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tables/': {
      id: '/_authenticated/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof AuthenticatedTablesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pages/': {
      id: '/_authenticated/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthenticatedPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal/': {
      id: '/_authenticated/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof AuthenticatedJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tables/$tableId': {
      id: '/_authenticated/tables/$tableId'
      path: '/tables/$tableId'
      fullPath: '/tables/$tableId'
      preLoaderRoute: typeof AuthenticatedTablesTableIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pages/$pageId': {
      id: '/_authenticated/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof AuthenticatedPagesPageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal/_layout': {
      id: '/_authenticated/journal/_layout'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal/$pageId': {
      id: '/_authenticated/journal/$pageId'
      path: '/journal/$pageId'
      fullPath: '/journal/$pageId'
      preLoaderRoute: typeof AuthenticatedJournalPageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tables/$tableId/settings': {
      id: '/_authenticated/tables/$tableId/settings'
      path: '/settings'
      fullPath: '/tables/$tableId/settings'
      preLoaderRoute: typeof AuthenticatedTablesTableIdSettingsRouteImport
      parentRoute: typeof AuthenticatedTablesTableIdRoute
    }
    '/_authenticated/tables/$tableId/rows/$rowId': {
      id: '/_authenticated/tables/$tableId/rows/$rowId'
      path: '/rows/$rowId'
      fullPath: '/tables/$tableId/rows/$rowId'
      preLoaderRoute: typeof AuthenticatedTablesTableIdRowsRowIdRouteImport
      parentRoute: typeof AuthenticatedTablesTableIdRoute
    }
  }
}

interface AuthenticatedTablesTableIdRouteChildren {
  AuthenticatedTablesTableIdSettingsRoute: typeof AuthenticatedTablesTableIdSettingsRoute
  AuthenticatedTablesTableIdRowsRowIdRoute: typeof AuthenticatedTablesTableIdRowsRowIdRoute
}

const AuthenticatedTablesTableIdRouteChildren: AuthenticatedTablesTableIdRouteChildren =
  {
    AuthenticatedTablesTableIdSettingsRoute:
      AuthenticatedTablesTableIdSettingsRoute,
    AuthenticatedTablesTableIdRowsRowIdRoute:
      AuthenticatedTablesTableIdRowsRowIdRoute,
  }

const AuthenticatedTablesTableIdRouteWithChildren =
  AuthenticatedTablesTableIdRoute._addFileChildren(
    AuthenticatedTablesTableIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedJournalPageIdRoute: typeof AuthenticatedJournalPageIdRoute
  AuthenticatedJournalLayoutRoute: typeof AuthenticatedJournalLayoutRoute
  AuthenticatedPagesPageIdRoute: typeof AuthenticatedPagesPageIdRoute
  AuthenticatedTablesTableIdRoute: typeof AuthenticatedTablesTableIdRouteWithChildren
  AuthenticatedJournalIndexRoute: typeof AuthenticatedJournalIndexRoute
  AuthenticatedPagesIndexRoute: typeof AuthenticatedPagesIndexRoute
  AuthenticatedTablesIndexRoute: typeof AuthenticatedTablesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedJournalPageIdRoute: AuthenticatedJournalPageIdRoute,
  AuthenticatedJournalLayoutRoute: AuthenticatedJournalLayoutRoute,
  AuthenticatedPagesPageIdRoute: AuthenticatedPagesPageIdRoute,
  AuthenticatedTablesTableIdRoute: AuthenticatedTablesTableIdRouteWithChildren,
  AuthenticatedJournalIndexRoute: AuthenticatedJournalIndexRoute,
  AuthenticatedPagesIndexRoute: AuthenticatedPagesIndexRoute,
  AuthenticatedTablesIndexRoute: AuthenticatedTablesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminInviteRoute: AdminInviteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
